import type { Knex } from 'knex';

/**
 * Migration: Add TestProducts permissions and roles
 * Generated by CRUD Generator on 2025-11-03T04:45:09.940Z
 */

export async function up(knex: Knex): Promise<void> {
  console.log('🔐 Adding TestProducts permissions and roles...');

  // Insert permissions for testProducts
  const permissions = [
    {
      description: 'Create testProducts',
      resource: 'testProducts',
      action: 'create',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Read testProducts',
      resource: 'testProducts',
      action: 'read',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Update testProducts',
      resource: 'testProducts',
      action: 'update',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Delete testProducts',
      resource: 'testProducts',
      action: 'delete',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(
    `📝 Inserting ${permissions.length} permissions for testProducts...`,
  );
  await knex('permissions')
    .insert(permissions)
    .onConflict(['resource', 'action'])
    .ignore();

  // Insert roles for testProducts
  const roles = [
    {
      name: 'testProducts',
      description: 'Access to testProducts',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`🏷️  Inserting ${roles.length} roles for testProducts...`);
  await knex('roles').insert(roles).onConflict('name').ignore();

  // Link role permissions
  // testProducts role permissions
  const mainRole = await knex('roles').where('name', 'testProducts').first();
  if (mainRole) {
    const mainPermissions = await knex('permissions')
      .where('resource', 'testProducts')
      .whereIn('action', ['create', 'read', 'update', 'delete'])
      .select('id');

    if (mainPermissions.length > 0) {
      const rolePermissions = mainPermissions.map((p) => ({
        role_id: mainRole.id,
        permission_id: p.id,
        created_at: new Date(),
      }));

      console.log(
        `🔗 Linking ${mainPermissions.length} permissions to testProducts role...`,
      );
      await knex('role_permissions')
        .insert(rolePermissions)
        .onConflict(['role_id', 'permission_id'])
        .ignore();
    }
  }

  console.log('✅ TestProducts permissions and roles added successfully');
}

export async function down(knex: Knex): Promise<void> {
  console.log('🗑️  Removing TestProducts permissions and roles...');

  // Remove role permissions first
  const roleIds = await knex('roles')
    .whereIn('name', ['testProducts'])
    .pluck('id');

  if (roleIds.length > 0) {
    console.log(`🔗 Removing role permissions for testProducts...`);
    await knex('role_permissions').whereIn('role_id', roleIds).del();
  }

  // Remove roles
  console.log(`🏷️  Removing testProducts role...`);
  const deletedRoles = await knex('roles')
    .whereIn('name', ['testProducts'])
    .del();

  // Remove permissions
  console.log(`📝 Removing testProducts permissions...`);
  const deletedPermissions = await knex('permissions')
    .where('resource', 'testProducts')
    .del();

  console.log(
    `✅ Removed ${deletedRoles} roles and ${deletedPermissions} permissions for testProducts`,
  );
}
