/**
 * Migration: Add TestProducts Permissions
 *
 * Creates testProducts role and permissions with role hierarchy support.
 * The testProducts role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates testProducts role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: testProducts (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under testProducts later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: testProducts
 * Generated: 2025-11-27T16:15:27.086Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from './helpers/permission-helper.js';

/**
 * TestProducts permissions definition
 */
const TESTPRODUCTS_PERMISSIONS = [
  {
    resource: 'testProducts',
    action: 'create',
    description: 'Create testProducts',
  },
  {
    resource: 'testProducts',
    action: 'read',
    description: 'Read testProducts',
  },
  {
    resource: 'testProducts',
    action: 'update',
    description: 'Update testProducts',
  },
  {
    resource: 'testProducts',
    action: 'delete',
    description: 'Delete testProducts',
  },
  {
    resource: 'testProducts',
    action: 'export',
    description: 'Export testProducts',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating testProducts role and permissions...');

  // Step 1: Create testProducts role with admin as parent
  // This ensures testProducts role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'testProducts',
    'TestProducts module role',
    'admin',
  );

  // Step 2: Create permissions and assign to testProducts role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, TESTPRODUCTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'testProducts',
        permissions: TESTPRODUCTS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] TestProducts role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing testProducts permissions...');

  await removePermissions(knex, TESTPRODUCTS_PERMISSIONS);

  console.log('[Migration] TestProducts permissions removed successfully');
}
