/**
 * Migration: Add TestCategories Permissions
 *
 * Creates testCategories role and permissions with role hierarchy support.
 * The testCategories role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates testCategories role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: testCategories (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under testCategories later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: testCategories
 * Generated: 2025-11-05T14:42:37.140Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from './helpers/permission-helper.js';

/**
 * TestCategories permissions definition
 */
const TESTCATEGORIES_PERMISSIONS = [
  {
    resource: 'testCategories',
    action: 'create',
    description: 'Create testCategories',
  },
  {
    resource: 'testCategories',
    action: 'read',
    description: 'Read testCategories',
  },
  {
    resource: 'testCategories',
    action: 'update',
    description: 'Update testCategories',
  },
  {
    resource: 'testCategories',
    action: 'delete',
    description: 'Delete testCategories',
  },
  {
    resource: 'testCategories',
    action: 'export',
    description: 'Export testCategories',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating testCategories role and permissions...');

  // Step 1: Create testCategories role with admin as parent
  // This ensures testCategories role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'testCategories',
    'TestCategories module role',
    'admin'
  );

  // Step 2: Create permissions and assign to testCategories role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, TESTCATEGORIES_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'testCategories',
        permissions: TESTCATEGORIES_PERMISSIONS,
      },
    ],
  });

  console.log('[Migration] TestCategories role and permissions created successfully');
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing testCategories permissions...');

  await removePermissions(knex, TESTCATEGORIES_PERMISSIONS);

  console.log('[Migration] TestCategories permissions removed successfully');
}