import { Knex } from 'knex';

/**
 * Migration: Add UserRoles permissions and roles
 * Generated by CRUD Generator on 2025-09-28T02:29:13.280Z
 */

export async function up(knex: Knex): Promise<void> {
  console.log('🔐 Adding UserRoles permissions and roles...');

  // Insert permissions for userRoles
  const permissions = [
    {
      name: 'userRoles.create',
      description: 'Create userRoles',
      resource: 'userRoles',
      action: 'create',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: 'userRoles.read',
      description: 'Read userRoles',
      resource: 'userRoles',
      action: 'read',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: 'userRoles.update',
      description: 'Update userRoles',
      resource: 'userRoles',
      action: 'update',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: 'userRoles.delete',
      description: 'Delete userRoles',
      resource: 'userRoles',
      action: 'delete',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(
    `📝 Inserting ${permissions.length} permissions for userRoles...`,
  );
  await knex('permissions').insert(permissions).onConflict('name').ignore();

  // Insert roles for userRoles
  const roles = [
    {
      name: 'userRoles',
      description: 'Access to userRoles',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`🏷️  Inserting ${roles.length} roles for userRoles...`);
  await knex('roles').insert(roles).onConflict('name').ignore();

  // Link role permissions
  // userRoles role permissions
  const mainRole = await knex('roles').where('name', 'userRoles').first();
  if (mainRole) {
    const mainPermissions = await knex('permissions')
      .whereIn('name', [
        'userRoles.create',
        'userRoles.read',
        'userRoles.update',
        'userRoles.delete',
      ])
      .select('id');

    if (mainPermissions.length > 0) {
      const rolePermissions = mainPermissions.map((p) => ({
        role_id: mainRole.id,
        permission_id: p.id,
        created_at: new Date(),
      }));

      console.log(
        `🔗 Linking $mainPermissions.length} permissions to userRoles role...`,
      );
      await knex('role_permissions')
        .insert(rolePermissions)
        .onConflict(['role_id', 'permission_id'])
        .ignore();
    }
  }

  console.log('✅ UserRoles permissions and roles added successfully');
}

export async function down(knex: Knex): Promise<void> {
  console.log('🗑️  Removing UserRoles permissions and roles...');

  // Remove role permissions first
  const roleIds = await knex('roles')
    .whereIn('name', ['userRoles'])
    .pluck('id');

  if (roleIds.length > 0) {
    console.log(`🔗 Removing role permissions for userRoles...`);
    await knex('role_permissions').whereIn('role_id', roleIds).del();
  }

  // Remove roles
  console.log(`🏷️  Removing userRoles role...`);
  const deletedRoles = await knex('roles').whereIn('name', ['userRoles']).del();

  // Remove permissions
  console.log(`📝 Removing userRoles permissions...`);
  const deletedPermissions = await knex('permissions')
    .where('resource', 'userRoles')
    .del();

  console.log(
    `✅ Removed ${deletedRoles} roles and ${deletedPermissions} permissions for userRoles`,
  );
}
