import { Knex } from 'knex';

/**
 * Migration: Add Notifications permissions and roles
 * Generated by CRUD Generator on 2025-09-28T02:40:52.734Z
 */

export async function up(knex: Knex): Promise<void> {
  console.log('🔐 Adding Notifications permissions and roles...');

  // Insert permissions for notifications
  const permissions = [
    {
      name: 'notifications.create',
      description: 'Create notifications',
      resource: 'notifications',
      action: 'create',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: 'notifications.read',
      description: 'Read notifications',
      resource: 'notifications',
      action: 'read',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: 'notifications.update',
      description: 'Update notifications',
      resource: 'notifications',
      action: 'update',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: 'notifications.delete',
      description: 'Delete notifications',
      resource: 'notifications',
      action: 'delete',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(
    `📝 Inserting ${permissions.length} permissions for notifications...`,
  );
  await knex('permissions').insert(permissions).onConflict('name').ignore();

  // Insert roles for notifications
  const roles = [
    {
      name: 'notifications',
      description: 'Access to notifications',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`🏷️  Inserting ${roles.length} roles for notifications...`);
  await knex('roles').insert(roles).onConflict('name').ignore();

  // Link role permissions
  // notifications role permissions
  const mainRole = await knex('roles').where('name', 'notifications').first();
  if (mainRole) {
    const mainPermissions = await knex('permissions')
      .whereIn('name', [
        'notifications.create',
        'notifications.read',
        'notifications.update',
        'notifications.delete',
      ])
      .select('id');

    if (mainPermissions.length > 0) {
      const rolePermissions = mainPermissions.map((p) => ({
        role_id: mainRole.id,
        permission_id: p.id,
        created_at: new Date(),
      }));

      console.log(
        `🔗 Linking $mainPermissions.length} permissions to notifications role...`,
      );
      await knex('role_permissions')
        .insert(rolePermissions)
        .onConflict(['role_id', 'permission_id'])
        .ignore();
    }
  }

  console.log('✅ Notifications permissions and roles added successfully');
}

export async function down(knex: Knex): Promise<void> {
  console.log('🗑️  Removing Notifications permissions and roles...');

  // Remove role permissions first
  const roleIds = await knex('roles')
    .whereIn('name', ['notifications'])
    .pluck('id');

  if (roleIds.length > 0) {
    console.log(`🔗 Removing role permissions for notifications...`);
    await knex('role_permissions').whereIn('role_id', roleIds).del();
  }

  // Remove roles
  console.log(`🏷️  Removing notifications role...`);
  const deletedRoles = await knex('roles')
    .whereIn('name', ['notifications'])
    .del();

  // Remove permissions
  console.log(`📝 Removing notifications permissions...`);
  const deletedPermissions = await knex('permissions')
    .where('resource', 'notifications')
    .del();

  console.log(
    `✅ Removed ${deletedRoles} roles and ${deletedPermissions} permissions for notifications`,
  );
}
