/**
 * Migration: Add Drugs Permissions
 *
 * Creates drugs role and permissions with role hierarchy support.
 * The drugs role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugs role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: drugs (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugs later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: drugs
 * Generated: 2025-12-06T22:51:20.127Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from './helpers/permission-helper.js';

/**
 * Drugs permissions definition
 */
const DRUGS_PERMISSIONS = [
  {
    resource: 'drugs',
    action: 'create',
    description: 'Create drugs',
  },
  {
    resource: 'drugs',
    action: 'read',
    description: 'Read drugs',
  },
  {
    resource: 'drugs',
    action: 'update',
    description: 'Update drugs',
  },
  {
    resource: 'drugs',
    action: 'delete',
    description: 'Delete drugs',
  },
  {
    resource: 'drugs',
    action: 'export',
    description: 'Export drugs',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating drugs role and permissions...');

  // Step 1: Create drugs role with admin as parent
  // This ensures drugs role is part of the hierarchy
  await createRoleIfNotExists(knex, 'drugs', 'Drugs module role', 'admin');

  // Step 2: Create permissions and assign to drugs role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, DRUGS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugs',
        permissions: DRUGS_PERMISSIONS,
      },
    ],
  });

  console.log('[Migration] Drugs role and permissions created successfully');
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugs permissions...');

  await removePermissions(knex, DRUGS_PERMISSIONS);

  console.log('[Migration] Drugs permissions removed successfully');
}
