import type { Knex } from 'knex';

/**
 * Migration: Add Books permissions and roles
 * Generated by CRUD Generator on 2025-10-06T07:28:22.072Z
 */

export async function up(knex: Knex): Promise<void> {
  console.log('🔐 Adding Books permissions and roles...');

  // Insert permissions for books
  const permissions = [
    {
      description: 'Create books',
      resource: 'books',
      action: 'create',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Read books',
      resource: 'books',
      action: 'read',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Update books',
      resource: 'books',
      action: 'update',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Delete books',
      resource: 'books',
      action: 'delete',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`📝 Inserting ${permissions.length} permissions for books...`);
  await knex('permissions')
    .insert(permissions)
    .onConflict(['resource', 'action'])
    .ignore();

  // Insert roles for books
  const roles = [
    {
      name: 'books',
      description: 'Access to books',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`🏷️  Inserting ${roles.length} roles for books...`);
  await knex('roles').insert(roles).onConflict('name').ignore();

  // Link role permissions
  // books role permissions
  const mainRole = await knex('roles').where('name', 'books').first();
  if (mainRole) {
    const mainPermissions = await knex('permissions')
      .where('resource', 'books')
      .whereIn('action', ['create', 'read', 'update', 'delete'])
      .select('id');

    if (mainPermissions.length > 0) {
      const rolePermissions = mainPermissions.map((p) => ({
        role_id: mainRole.id,
        permission_id: p.id,
        created_at: new Date(),
      }));

      console.log(
        `🔗 Linking ${mainPermissions.length} permissions to books role...`,
      );
      await knex('role_permissions')
        .insert(rolePermissions)
        .onConflict(['role_id', 'permission_id'])
        .ignore();
    }
  }

  console.log('✅ Books permissions and roles added successfully');
}

export async function down(knex: Knex): Promise<void> {
  console.log('🗑️  Removing Books permissions and roles...');

  // Remove role permissions first
  const roleIds = await knex('roles').whereIn('name', ['books']).pluck('id');

  if (roleIds.length > 0) {
    console.log(`🔗 Removing role permissions for books...`);
    await knex('role_permissions').whereIn('role_id', roleIds).del();
  }

  // Remove roles
  console.log(`🏷️  Removing books role...`);
  const deletedRoles = await knex('roles').whereIn('name', ['books']).del();

  // Remove permissions
  console.log(`📝 Removing books permissions...`);
  const deletedPermissions = await knex('permissions')
    .where('resource', 'books')
    .del();

  console.log(
    `✅ Removed ${deletedRoles} roles and ${deletedPermissions} permissions for books`,
  );
}
