import type { Knex } from 'knex';

/**
 * Migration: Add Budgets permissions and roles
 * Generated by CRUD Generator on 2025-10-26T06:22:38.623Z
 */

export async function up(knex: Knex): Promise<void> {
  console.log('🔐 Adding Budgets permissions and roles...');

  // Insert permissions for budgets
  const permissions = [
    {
      description: 'Create budgets', 
      resource: 'budgets',
      action: 'create',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      description: 'Read budgets', 
      resource: 'budgets',
      action: 'read',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      description: 'Update budgets', 
      resource: 'budgets',
      action: 'update',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      description: 'Delete budgets', 
      resource: 'budgets',
      action: 'delete',
      created_at: new Date(),
      updated_at: new Date()
    }
  ];

  console.log(`📝 Inserting ${permissions.length} permissions for budgets...`);
  await knex('permissions')
    .insert(permissions)
    .onConflict(['resource', 'action'])
    .ignore();

  // Insert roles for budgets
  const roles = [
    {
      name: 'budgets',
      description: 'Access to budgets',
      created_at: new Date(),
      updated_at: new Date()
    }
  ];

  console.log(`🏷️  Inserting ${roles.length} roles for budgets...`);
  await knex('roles')
    .insert(roles)
    .onConflict('name')
    .ignore();

  // Link role permissions
  // budgets role permissions
  const mainRole = await knex('roles').where('name', 'budgets').first();
  if (mainRole) {
    const mainPermissions = await knex('permissions')
      .where('resource', 'budgets')
      .whereIn('action', ["create","read","update","delete"])
      .select('id');
    
    if (mainPermissions.length > 0) {
      const rolePermissions = mainPermissions.map(p => ({
        role_id: mainRole.id,
        permission_id: p.id,
        created_at: new Date()
      }));

      console.log(`🔗 Linking ${ mainPermissions.length} permissions to budgets role...`);
      await knex('role_permissions')
        .insert(rolePermissions)
        .onConflict(['role_id', 'permission_id'])
        .ignore();
    }
  }

  console.log('✅ Budgets permissions and roles added successfully');
}

export async function down(knex: Knex): Promise<void> {
  console.log('🗑️  Removing Budgets permissions and roles...');

  // Remove role permissions first
  const roleIds = await knex('roles')
    .whereIn('name', ['budgets'])
    .pluck('id');

  if (roleIds.length > 0) {
    console.log(`🔗 Removing role permissions for budgets...`);
    await knex('role_permissions')
      .whereIn('role_id', roleIds)
      .del();
  }

  // Remove roles
  console.log(`🏷️  Removing budgets role...`);
  const deletedRoles = await knex('roles')
    .whereIn('name', ['budgets'])
    .del();

  // Remove permissions  
  console.log(`📝 Removing budgets permissions...`);
  const deletedPermissions = await knex('permissions')
    .where('resource', 'budgets')
    .del();

  console.log(`✅ Removed ${deletedRoles} roles and ${deletedPermissions} permissions for budgets`);
}