import { Knex } from 'knex';

/**
 * Migration: Add Themes permissions and roles
 * Generated by CRUD Generator on 2025-09-27T06:52:35.419Z
 */

export async function up(knex: Knex): Promise<void> {
  console.log('🔐 Adding Themes permissions and roles...');

  // Insert permissions for themes
  const permissions = [
    {
      name: 'themes.create',
      description: 'Create themes',
      resource: 'themes',
      action: 'create',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: 'themes.read',
      description: 'Read themes',
      resource: 'themes',
      action: 'read',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: 'themes.update',
      description: 'Update themes',
      resource: 'themes',
      action: 'update',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: 'themes.delete',
      description: 'Delete themes',
      resource: 'themes',
      action: 'delete',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`📝 Inserting ${permissions.length} permissions for themes...`);
  await knex('permissions').insert(permissions).onConflict('name').ignore();

  // Insert roles for themes
  const roles = [
    {
      name: 'themes',
      description: 'Access to themes',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`🏷️  Inserting ${roles.length} roles for themes...`);
  await knex('roles').insert(roles).onConflict('name').ignore();

  // Link role permissions
  // themes role permissions
  const mainRole = await knex('roles').where('name', 'themes').first();
  if (mainRole) {
    const mainPermissions = await knex('permissions')
      .whereIn('name', [
        'themes.create',
        'themes.read',
        'themes.update',
        'themes.delete',
      ])
      .select('id');

    if (mainPermissions.length > 0) {
      const rolePermissions = mainPermissions.map((p) => ({
        role_id: mainRole.id,
        permission_id: p.id,
        created_at: new Date(),
      }));

      console.log(
        `🔗 Linking $mainPermissions.length} permissions to themes role...`,
      );
      await knex('role_permissions')
        .insert(rolePermissions)
        .onConflict(['role_id', 'permission_id'])
        .ignore();
    }
  }

  console.log('✅ Themes permissions and roles added successfully');
}

export async function down(knex: Knex): Promise<void> {
  console.log('🗑️  Removing Themes permissions and roles...');

  // Remove role permissions first
  const roleIds = await knex('roles').whereIn('name', ['themes']).pluck('id');

  if (roleIds.length > 0) {
    console.log(`🔗 Removing role permissions for themes...`);
    await knex('role_permissions').whereIn('role_id', roleIds).del();
  }

  // Remove roles
  console.log(`🏷️  Removing themes role...`);
  const deletedRoles = await knex('roles').whereIn('name', ['themes']).del();

  // Remove permissions
  console.log(`📝 Removing themes permissions...`);
  const deletedPermissions = await knex('permissions')
    .where('resource', 'themes')
    .del();

  console.log(
    `✅ Removed ${deletedRoles} roles and ${deletedPermissions} permissions for themes`,
  );
}
