/**
 * CSS Generator Utilities
 * Generates CSS, SCSS, and Tailwind config from theme definitions
 */

import {
  ThemeDefinition,
  ThemeColorSlots,
  ThemeDesignTokens,
  ExportOptions,
  AX_VARIABLE_MAPPINGS,
  OklchColor,
} from '../models/theme-generator.types';
import { oklchToString, oklchToHex } from './oklch.utils';

// ============================================================================
// CSS Variable Generation
// ============================================================================

/**
 * Generate CSS variables from theme definition
 */
export function generateCSSVariables(
  theme: ThemeDefinition,
  options: Partial<ExportOptions> = {},
): string {
  const prefix = options.variablePrefix || 'ax';
  const includeComments = options.includeComments ?? true;
  const lines: string[] = [];

  // Header comment
  if (includeComments) {
    lines.push(`/* Theme: ${theme.displayName} */`);
    lines.push(`/* Generated by AegisX Theme Generator */`);
    lines.push(`/* Color Scheme: ${theme.colorScheme} */`);
    lines.push('');
  }

  // Open selector
  lines.push(`[data-theme="${theme.name}"] {`);

  // Color scheme
  lines.push(`  color-scheme: ${theme.colorScheme};`);
  lines.push('');

  // Base colors section
  if (includeComments) lines.push('  /* Base Colors */');
  lines.push(...generateColorVariables(theme.colors, prefix, '  '));
  lines.push('');

  // Design tokens section
  if (includeComments) lines.push('  /* Design Tokens */');
  lines.push(...generateTokenVariables(theme.tokens, prefix, '  '));
  lines.push('');

  // Backward compatibility mappings
  if (includeComments)
    lines.push('  /* Backward Compatibility (--ax-* variables) */');
  lines.push(...generateBackwardCompatVariables(theme.colors, '  '));

  // Close selector
  lines.push('}');

  return options.minify ? minifyCSS(lines.join('\n')) : lines.join('\n');
}

/**
 * Generate color CSS variables
 */
function generateColorVariables(
  colors: ThemeColorSlots,
  prefix: string,
  indent: string,
): string[] {
  const lines: string[] = [];
  const colorSlots = Object.entries(colors) as [
    keyof ThemeColorSlots,
    OklchColor,
  ][];

  for (const [slot, color] of colorSlots) {
    const varName = `--${prefix}-color-${slot}`;
    const value = oklchToString(color);
    lines.push(`${indent}${varName}: ${value};`);
  }

  return lines;
}

/**
 * Generate design token CSS variables
 */
function generateTokenVariables(
  tokens: ThemeDesignTokens,
  prefix: string,
  indent: string,
): string[] {
  const lines: string[] = [];

  lines.push(
    `${indent}--${prefix}-radius-selector: ${tokens['radius-selector']};`,
  );
  lines.push(`${indent}--${prefix}-radius-field: ${tokens['radius-field']};`);
  lines.push(`${indent}--${prefix}-radius-box: ${tokens['radius-box']};`);
  lines.push(`${indent}--${prefix}-size-selector: ${tokens['size-selector']};`);
  lines.push(`${indent}--${prefix}-size-field: ${tokens['size-field']};`);
  lines.push(`${indent}--${prefix}-border: ${tokens.border};`);
  lines.push(`${indent}--${prefix}-depth: ${tokens.depth};`);
  lines.push(`${indent}--${prefix}-noise: ${tokens.noise};`);

  return lines;
}

/**
 * Generate backward compatibility variables (map to existing --ax-* vars)
 */
function generateBackwardCompatVariables(
  colors: ThemeColorSlots,
  indent: string,
): string[] {
  const lines: string[] = [];

  for (const mapping of AX_VARIABLE_MAPPINGS) {
    const color = colors[mapping.slot];
    if (!color) continue;

    const value = oklchToString(color);
    for (const axVar of mapping.axVariables) {
      lines.push(`${indent}${axVar}: ${value};`);
    }
  }

  return lines;
}

// ============================================================================
// SCSS Generation
// ============================================================================

/**
 * Generate SCSS mixin from theme definition
 */
export function generateSCSSMixin(
  theme: ThemeDefinition,
  options: Partial<ExportOptions> = {},
): string {
  const includeComments = options.includeComments ?? true;
  const lines: string[] = [];

  // Header
  if (includeComments) {
    lines.push(`/// Theme: ${theme.displayName}`);
    lines.push(`/// Generated by AegisX Theme Generator`);
    lines.push('');
  }

  // SCSS variables for colors
  lines.push('// Color Definitions');
  const colorSlots = Object.entries(theme.colors) as [
    keyof ThemeColorSlots,
    OklchColor,
  ][];
  for (const [slot, color] of colorSlots) {
    const varName = `$theme-${slot}`;
    const value = oklchToString(color);
    lines.push(`${varName}: ${value};`);
  }
  lines.push('');

  // Mixin
  lines.push(`@mixin theme-${theme.name}() {`);

  // Color scheme
  lines.push(`  color-scheme: ${theme.colorScheme};`);
  lines.push('');

  // Color variables
  for (const [slot, color] of colorSlots) {
    const value = oklchToString(color);
    lines.push(`  --ax-color-${slot}: ${value};`);
  }
  lines.push('');

  // Design tokens
  lines.push(`  --ax-radius-selector: ${theme.tokens['radius-selector']};`);
  lines.push(`  --ax-radius-field: ${theme.tokens['radius-field']};`);
  lines.push(`  --ax-radius-box: ${theme.tokens['radius-box']};`);
  lines.push('');

  // Backward compat
  for (const mapping of AX_VARIABLE_MAPPINGS) {
    const color = theme.colors[mapping.slot];
    if (!color) continue;
    const value = oklchToString(color);
    for (const axVar of mapping.axVariables) {
      lines.push(`  ${axVar}: ${value};`);
    }
  }

  lines.push('}');
  lines.push('');

  // Usage example
  if (includeComments) {
    lines.push('// Usage:');
    lines.push(
      `// [data-theme="${theme.name}"] { @include theme-${theme.name}(); }`,
    );
  }

  return lines.join('\n');
}

// ============================================================================
// Tailwind Config Generation
// ============================================================================

/**
 * Generate Tailwind CSS config extend object
 */
export function generateTailwindConfig(
  theme: ThemeDefinition,
  options: Partial<ExportOptions> = {},
): string {
  const includeComments = options.includeComments ?? true;
  const lines: string[] = [];

  if (includeComments) {
    lines.push(`// Theme: ${theme.displayName}`);
    lines.push('// Add to tailwind.config.js extend.colors');
    lines.push('');
  }

  lines.push('module.exports = {');
  lines.push('  theme: {');
  lines.push('    extend: {');
  lines.push('      colors: {');

  // Map theme colors to Tailwind
  const colorGroups = [
    { name: 'primary', slots: ['primary', 'primary-content'] },
    { name: 'secondary', slots: ['secondary', 'secondary-content'] },
    { name: 'accent', slots: ['accent', 'accent-content'] },
    { name: 'neutral', slots: ['neutral', 'neutral-content'] },
    {
      name: 'base',
      slots: ['base-100', 'base-200', 'base-300', 'base-content'],
    },
    { name: 'info', slots: ['info', 'info-content'] },
    { name: 'success', slots: ['success', 'success-content'] },
    { name: 'warning', slots: ['warning', 'warning-content'] },
    { name: 'error', slots: ['error', 'error-content'] },
  ];

  for (const group of colorGroups) {
    lines.push(`        ${group.name}: {`);
    for (const slot of group.slots) {
      const color = theme.colors[slot as keyof ThemeColorSlots];
      if (color) {
        const key = slot
          .replace(`${group.name}-`, '')
          .replace(group.name, 'DEFAULT');
        lines.push(
          `          ${key === group.name ? 'DEFAULT' : key}: 'var(--ax-color-${slot})',`,
        );
      }
    }
    lines.push('        },');
  }

  lines.push('      },');
  lines.push('      borderRadius: {');
  lines.push("        selector: 'var(--ax-radius-selector)',");
  lines.push("        field: 'var(--ax-radius-field)',");
  lines.push("        box: 'var(--ax-radius-box)',");
  lines.push('      },');
  lines.push('    },');
  lines.push('  },');
  lines.push('};');

  return lines.join('\n');
}

// ============================================================================
// JSON Export
// ============================================================================

/**
 * Export theme as JSON
 */
export function generateJSON(theme: ThemeDefinition): string {
  // Convert OKLCH to both oklch string and hex for usability
  const colorsWithHex: Record<string, { oklch: string; hex: string }> = {};
  const colorSlots = Object.entries(theme.colors) as [
    keyof ThemeColorSlots,
    OklchColor,
  ][];

  for (const [slot, color] of colorSlots) {
    colorsWithHex[slot] = {
      oklch: oklchToString(color),
      hex: oklchToHex(color),
    };
  }

  return JSON.stringify(
    {
      name: theme.name,
      displayName: theme.displayName,
      colorScheme: theme.colorScheme,
      colors: colorsWithHex,
      tokens: theme.tokens,
      generatedAt: new Date().toISOString(),
      generator: 'AegisX Theme Generator',
    },
    null,
    2,
  );
}

// ============================================================================
// DaisyUI Format (for reference/compatibility)
// ============================================================================

/**
 * Generate DaisyUI @plugin format
 * This is for reference - shows how our theme maps to DaisyUI
 */
export function generateDaisyUIFormat(theme: ThemeDefinition): string {
  const lines: string[] = [];

  lines.push('@plugin "daisyui/theme" {');
  lines.push(`  name: "${theme.name}";`);
  lines.push(`  default: ${theme.isDefault ? 'true' : 'false'};`);
  lines.push(`  prefersdark: ${theme.prefersDark ? 'true' : 'false'};`);
  lines.push(`  color-scheme: "${theme.colorScheme}";`);

  // Colors
  const colorSlots = Object.entries(theme.colors) as [
    keyof ThemeColorSlots,
    OklchColor,
  ][];
  for (const [slot, color] of colorSlots) {
    lines.push(`  --color-${slot}: ${oklchToString(color)};`);
  }

  // Design tokens
  lines.push(`  --radius-selector: ${theme.tokens['radius-selector']};`);
  lines.push(`  --radius-field: ${theme.tokens['radius-field']};`);
  lines.push(`  --radius-box: ${theme.tokens['radius-box']};`);
  lines.push(`  --size-selector: ${theme.tokens['size-selector']};`);
  lines.push(`  --size-field: ${theme.tokens['size-field']};`);
  lines.push(`  --border: ${theme.tokens.border};`);
  lines.push(`  --depth: ${theme.tokens.depth};`);
  lines.push(`  --noise: ${theme.tokens.noise};`);

  lines.push('}');

  return lines.join('\n');
}

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Minify CSS
 */
function minifyCSS(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '') // Remove comments
    .replace(/\s+/g, ' ') // Collapse whitespace
    .replace(/\s*([{}:;,])\s*/g, '$1') // Remove space around special chars
    .replace(/;}/g, '}') // Remove last semicolon
    .trim();
}

/**
 * Generate full export based on format
 */
export function generateExport(
  theme: ThemeDefinition,
  options: ExportOptions,
): string {
  switch (options.format) {
    case 'css':
      return generateCSSVariables(theme, options);
    case 'scss':
      return generateSCSSMixin(theme, options);
    case 'tailwind':
      return generateTailwindConfig(theme, options);
    case 'json':
      return generateJSON(theme);
    default:
      return generateCSSVariables(theme, options);
  }
}

/**
 * Get file extension for export format
 */
export function getFileExtension(format: ExportOptions['format']): string {
  switch (format) {
    case 'css':
      return '.css';
    case 'scss':
      return '.scss';
    case 'tailwind':
      return '.js';
    case 'json':
      return '.json';
    default:
      return '.css';
  }
}

/**
 * Get MIME type for export format
 */
export function getMimeType(format: ExportOptions['format']): string {
  switch (format) {
    case 'css':
    case 'scss':
      return 'text/css';
    case 'tailwind':
      return 'text/javascript';
    case 'json':
      return 'application/json';
    default:
      return 'text/plain';
  }
}
