/**
 * Migration: Add DrugFocusLists Permissions
 *
 * Creates drugFocusLists role and permissions with role hierarchy support.
 * The drugFocusLists role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugFocusLists role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: drugFocusLists (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugFocusLists later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:drugFocusLists
 * Domain: inventory/master-data
 * Generated: 2025-12-08T02:04:50.277Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DrugFocusLists permissions definition
 */
const DRUGFOCUSLISTS_PERMISSIONS = [
  {
    resource: 'inventory:drugFocusLists',
    action: 'create',
    description: 'Create drugFocusLists',
  },
  {
    resource: 'inventory:drugFocusLists',
    action: 'read',
    description: 'Read drugFocusLists',
  },
  {
    resource: 'inventory:drugFocusLists',
    action: 'update',
    description: 'Update drugFocusLists',
  },
  {
    resource: 'inventory:drugFocusLists',
    action: 'delete',
    description: 'Delete drugFocusLists',
  },
  {
    resource: 'inventory:drugFocusLists',
    action: 'export',
    description: 'Export drugFocusLists',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating drugFocusLists role and permissions...');

  // Step 1: Create drugFocusLists role with admin as parent
  // This ensures drugFocusLists role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'drugFocusLists',
    'DrugFocusLists module role',
    'admin',
  );

  // Step 2: Create permissions and assign to drugFocusLists role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, DRUGFOCUSLISTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugFocusLists',
        permissions: DRUGFOCUSLISTS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] DrugFocusLists role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugFocusLists permissions...');

  await removePermissions(knex, DRUGFOCUSLISTS_PERMISSIONS);

  console.log('[Migration] DrugFocusLists permissions removed successfully');
}
