/**
 * Migration: Add BudgetTypes Permissions
 *
 * Creates budgetTypes role and permissions with role hierarchy support.
 * The budgetTypes role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates budgetTypes role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: budgetTypes (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under budgetTypes later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:budgetTypes
 * Domain: inventory/master-data
 * Generated: 2025-12-08T02:04:00.401Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * BudgetTypes permissions definition
 */
const BUDGETTYPES_PERMISSIONS = [
  {
    resource: 'inventory:budgetTypes',
    action: 'create',
    description: 'Create budgetTypes',
  },
  {
    resource: 'inventory:budgetTypes',
    action: 'read',
    description: 'Read budgetTypes',
  },
  {
    resource: 'inventory:budgetTypes',
    action: 'update',
    description: 'Update budgetTypes',
  },
  {
    resource: 'inventory:budgetTypes',
    action: 'delete',
    description: 'Delete budgetTypes',
  },
  {
    resource: 'inventory:budgetTypes',
    action: 'export',
    description: 'Export budgetTypes',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating budgetTypes role and permissions...');

  // Step 1: Create budgetTypes role with admin as parent
  // This ensures budgetTypes role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'budgetTypes',
    'BudgetTypes module role',
    'admin',
  );

  // Step 2: Create permissions and assign to budgetTypes role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, BUDGETTYPES_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'budgetTypes',
        permissions: BUDGETTYPES_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] BudgetTypes role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing budgetTypes permissions...');

  await removePermissions(knex, BUDGETTYPES_PERMISSIONS);

  console.log('[Migration] BudgetTypes permissions removed successfully');
}
