/**
 * Migration: Add ReturnReasons Permissions
 *
 * Creates returnReasons role and permissions with role hierarchy support.
 * The returnReasons role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates returnReasons role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: returnReasons (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under returnReasons later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:returnReasons
 * Domain: inventory/master-data
 * Generated: 2025-12-05T21:21:38.246Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * ReturnReasons permissions definition
 */
const RETURNREASONS_PERMISSIONS = [
  {
    resource: 'inventory:returnReasons',
    action: 'create',
    description: 'Create returnReasons',
  },
  {
    resource: 'inventory:returnReasons',
    action: 'read',
    description: 'Read returnReasons',
  },
  {
    resource: 'inventory:returnReasons',
    action: 'update',
    description: 'Update returnReasons',
  },
  {
    resource: 'inventory:returnReasons',
    action: 'delete',
    description: 'Delete returnReasons',
  },
  {
    resource: 'inventory:returnReasons',
    action: 'export',
    description: 'Export returnReasons',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating returnReasons role and permissions...');

  // Step 1: Create returnReasons role with admin as parent
  // This ensures returnReasons role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'returnReasons',
    'ReturnReasons module role',
    'admin',
  );

  // Step 2: Create permissions and assign to returnReasons role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, RETURNREASONS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'returnReasons',
        permissions: RETURNREASONS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] ReturnReasons role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing returnReasons permissions...');

  await removePermissions(knex, RETURNREASONS_PERMISSIONS);

  console.log('[Migration] ReturnReasons permissions removed successfully');
}
