/**
 * Migration: Add Hospitals Permissions
 *
 * Creates hospitals role and permissions with role hierarchy support.
 * The hospitals role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates hospitals role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: hospitals (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under hospitals later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:hospitals
 * Domain: inventory/master-data
 * Generated: 2025-12-08T02:05:25.379Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * Hospitals permissions definition
 */
const HOSPITALS_PERMISSIONS = [
  {
    resource: 'inventory:hospitals',
    action: 'create',
    description: 'Create hospitals',
  },
  {
    resource: 'inventory:hospitals',
    action: 'read',
    description: 'Read hospitals',
  },
  {
    resource: 'inventory:hospitals',
    action: 'update',
    description: 'Update hospitals',
  },
  {
    resource: 'inventory:hospitals',
    action: 'delete',
    description: 'Delete hospitals',
  },
  {
    resource: 'inventory:hospitals',
    action: 'export',
    description: 'Export hospitals',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating hospitals role and permissions...');

  // Step 1: Create hospitals role with admin as parent
  // This ensures hospitals role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'hospitals',
    'Hospitals module role',
    'admin',
  );

  // Step 2: Create permissions and assign to hospitals role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, HOSPITALS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'hospitals',
        permissions: HOSPITALS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] Hospitals role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing hospitals permissions...');

  await removePermissions(knex, HOSPITALS_PERMISSIONS);

  console.log('[Migration] Hospitals permissions removed successfully');
}
