/**
 * Migration: Add DosageForms Permissions
 *
 * Creates dosageForms role and permissions with role hierarchy support.
 * The dosageForms role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates dosageForms role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: dosageForms (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under dosageForms later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:dosageForms
 * Domain: inventory/master-data
 * Generated: 2025-12-08T02:04:35.739Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DosageForms permissions definition
 */
const DOSAGEFORMS_PERMISSIONS = [
  {
    resource: 'inventory:dosageForms',
    action: 'create',
    description: 'Create dosageForms',
  },
  {
    resource: 'inventory:dosageForms',
    action: 'read',
    description: 'Read dosageForms',
  },
  {
    resource: 'inventory:dosageForms',
    action: 'update',
    description: 'Update dosageForms',
  },
  {
    resource: 'inventory:dosageForms',
    action: 'delete',
    description: 'Delete dosageForms',
  },
  {
    resource: 'inventory:dosageForms',
    action: 'export',
    description: 'Export dosageForms',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating dosageForms role and permissions...');

  // Step 1: Create dosageForms role with admin as parent
  // This ensures dosageForms role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'dosageForms',
    'DosageForms module role',
    'admin',
  );

  // Step 2: Create permissions and assign to dosageForms role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, DOSAGEFORMS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'dosageForms',
        permissions: DOSAGEFORMS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] DosageForms role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing dosageForms permissions...');

  await removePermissions(knex, DOSAGEFORMS_PERMISSIONS);

  console.log('[Migration] DosageForms permissions removed successfully');
}
