/**
 * Migration: Add ContractItems Permissions
 *
 * Creates contractItems role and permissions with role hierarchy support.
 * The contractItems role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates contractItems role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: contractItems (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under contractItems later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:contractItems
 * Domain: inventory/master-data
 * Generated: 2025-12-07T07:36:59.074Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * ContractItems permissions definition
 */
const CONTRACTITEMS_PERMISSIONS = [
  {
    resource: 'inventory:contractItems',
    action: 'create',
    description: 'Create contractItems',
  },
  {
    resource: 'inventory:contractItems',
    action: 'read',
    description: 'Read contractItems',
  },
  {
    resource: 'inventory:contractItems',
    action: 'update',
    description: 'Update contractItems',
  },
  {
    resource: 'inventory:contractItems',
    action: 'delete',
    description: 'Delete contractItems',
  },
  {
    resource: 'inventory:contractItems',
    action: 'export',
    description: 'Export contractItems',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating contractItems role and permissions...');

  // Step 1: Create contractItems role with admin as parent
  // This ensures contractItems role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'contractItems',
    'ContractItems module role',
    'admin',
  );

  // Step 2: Create permissions and assign to contractItems role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, CONTRACTITEMS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'contractItems',
        permissions: CONTRACTITEMS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] ContractItems role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing contractItems permissions...');

  await removePermissions(knex, CONTRACTITEMS_PERMISSIONS);

  console.log('[Migration] ContractItems permissions removed successfully');
}
