/**
 * Migration: Add Departments Permissions
 *
 * Creates departments role and permissions with role hierarchy support.
 * The departments role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates departments role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: departments (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under departments later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:departments
 * Domain: inventory/master-data
 * Generated: 2025-12-07T07:35:02.464Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * Departments permissions definition
 */
const DEPARTMENTS_PERMISSIONS = [
  {
    resource: 'inventory:departments',
    action: 'create',
    description: 'Create departments',
  },
  {
    resource: 'inventory:departments',
    action: 'read',
    description: 'Read departments',
  },
  {
    resource: 'inventory:departments',
    action: 'update',
    description: 'Update departments',
  },
  {
    resource: 'inventory:departments',
    action: 'delete',
    description: 'Delete departments',
  },
  {
    resource: 'inventory:departments',
    action: 'export',
    description: 'Export departments',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating departments role and permissions...');

  // Step 1: Create departments role with admin as parent
  // This ensures departments role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'departments',
    'Departments module role',
    'admin',
  );

  // Step 2: Create permissions and assign to departments role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, DEPARTMENTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'departments',
        permissions: DEPARTMENTS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] Departments role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing departments permissions...');

  await removePermissions(knex, DEPARTMENTS_PERMISSIONS);

  console.log('[Migration] Departments permissions removed successfully');
}
