/**
 * Migration: Add Budgets Permissions
 *
 * Creates budgets role and permissions with role hierarchy support.
 * The budgets role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates budgets role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: budgets (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under budgets later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:budgets
 * Domain: inventory/master-data
 * Generated: 2025-12-08T02:03:53.457Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * Budgets permissions definition
 */
const BUDGETS_PERMISSIONS = [
  {
    resource: 'inventory:budgets',
    action: 'create',
    description: 'Create budgets',
  },
  {
    resource: 'inventory:budgets',
    action: 'read',
    description: 'Read budgets',
  },
  {
    resource: 'inventory:budgets',
    action: 'update',
    description: 'Update budgets',
  },
  {
    resource: 'inventory:budgets',
    action: 'delete',
    description: 'Delete budgets',
  },
  {
    resource: 'inventory:budgets',
    action: 'export',
    description: 'Export budgets',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating budgets role and permissions...');

  // Step 1: Create budgets role with admin as parent
  // This ensures budgets role is part of the hierarchy
  await createRoleIfNotExists(knex, 'budgets', 'Budgets module role', 'admin');

  // Step 2: Create permissions and assign to budgets role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, BUDGETS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'budgets',
        permissions: BUDGETS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log('[Migration] Budgets role and permissions created successfully');
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing budgets permissions...');

  await removePermissions(knex, BUDGETS_PERMISSIONS);

  console.log('[Migration] Budgets permissions removed successfully');
}
