/**
 * Migration: Add BudgetRequestItems Permissions
 *
 * Creates budgetRequestItems role and permissions with role hierarchy support.
 * The budgetRequestItems role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates budgetRequestItems role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: budgetRequestItems (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under budgetRequestItems later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:budgetRequestItems
 * Domain: inventory/budget
 * Generated: 2025-12-08T23:51:54.316Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * BudgetRequestItems permissions definition
 */
const BUDGETREQUESTITEMS_PERMISSIONS = [
  {
    resource: 'inventory:budgetRequestItems',
    action: 'create',
    description: 'Create budgetRequestItems',
  },
  {
    resource: 'inventory:budgetRequestItems',
    action: 'read',
    description: 'Read budgetRequestItems',
  },
  {
    resource: 'inventory:budgetRequestItems',
    action: 'update',
    description: 'Update budgetRequestItems',
  },
  {
    resource: 'inventory:budgetRequestItems',
    action: 'delete',
    description: 'Delete budgetRequestItems',
  },
  {
    resource: 'inventory:budgetRequestItems',
    action: 'export',
    description: 'Export budgetRequestItems',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating budgetRequestItems role and permissions...');

  // Step 1: Create budgetRequestItems role with admin as parent
  // This ensures budgetRequestItems role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'budgetRequestItems',
    'BudgetRequestItems module role',
    'admin'
  );

  // Step 2: Create permissions and assign to budgetRequestItems role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, BUDGETREQUESTITEMS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'budgetRequestItems',
        permissions: BUDGETREQUESTITEMS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log('[Migration] BudgetRequestItems role and permissions created successfully');
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing budgetRequestItems permissions...');

  await removePermissions(knex, BUDGETREQUESTITEMS_PERMISSIONS);

  console.log('[Migration] BudgetRequestItems permissions removed successfully');
}