/**
 * Migration: Add BudgetReservations Permissions
 *
 * Creates budgetReservations role and permissions with role hierarchy support.
 * The budgetReservations role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates budgetReservations role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: budgetReservations (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under budgetReservations later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:budgetReservations
 * Domain: inventory/operations
 * Generated: 2025-12-08T03:34:07.587Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * BudgetReservations permissions definition
 */
const BUDGETRESERVATIONS_PERMISSIONS = [
  {
    resource: 'inventory:budgetReservations',
    action: 'create',
    description: 'Create budgetReservations',
  },
  {
    resource: 'inventory:budgetReservations',
    action: 'read',
    description: 'Read budgetReservations',
  },
  {
    resource: 'inventory:budgetReservations',
    action: 'update',
    description: 'Update budgetReservations',
  },
  {
    resource: 'inventory:budgetReservations',
    action: 'delete',
    description: 'Delete budgetReservations',
  },
  {
    resource: 'inventory:budgetReservations',
    action: 'export',
    description: 'Export budgetReservations',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log(
    '[Migration] Creating budgetReservations role and permissions...',
  );

  // Step 1: Create budgetReservations role with admin as parent
  // This ensures budgetReservations role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'budgetReservations',
    'BudgetReservations module role',
    'admin',
  );

  // Step 2: Create permissions and assign to budgetReservations role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, BUDGETRESERVATIONS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'budgetReservations',
        permissions: BUDGETRESERVATIONS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] BudgetReservations role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing budgetReservations permissions...');

  await removePermissions(knex, BUDGETRESERVATIONS_PERMISSIONS);

  console.log(
    '[Migration] BudgetReservations permissions removed successfully',
  );
}
