/**
 * Migration: Add AdjustmentReasons Permissions
 *
 * Creates adjustmentReasons role and permissions with role hierarchy support.
 * The adjustmentReasons role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates adjustmentReasons role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: adjustmentReasons (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under adjustmentReasons later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:adjustmentReasons
 * Domain: inventory/master-data
 * Generated: 2025-12-05T21:20:20.411Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * AdjustmentReasons permissions definition
 */
const ADJUSTMENTREASONS_PERMISSIONS = [
  {
    resource: 'inventory:adjustmentReasons',
    action: 'create',
    description: 'Create adjustmentReasons',
  },
  {
    resource: 'inventory:adjustmentReasons',
    action: 'read',
    description: 'Read adjustmentReasons',
  },
  {
    resource: 'inventory:adjustmentReasons',
    action: 'update',
    description: 'Update adjustmentReasons',
  },
  {
    resource: 'inventory:adjustmentReasons',
    action: 'delete',
    description: 'Delete adjustmentReasons',
  },
  {
    resource: 'inventory:adjustmentReasons',
    action: 'export',
    description: 'Export adjustmentReasons',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating adjustmentReasons role and permissions...');

  // Step 1: Create adjustmentReasons role with admin as parent
  // This ensures adjustmentReasons role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'adjustmentReasons',
    'AdjustmentReasons module role',
    'admin',
  );

  // Step 2: Create permissions and assign to adjustmentReasons role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, ADJUSTMENTREASONS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'adjustmentReasons',
        permissions: ADJUSTMENTREASONS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] AdjustmentReasons role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing adjustmentReasons permissions...');

  await removePermissions(knex, ADJUSTMENTREASONS_PERMISSIONS);

  console.log('[Migration] AdjustmentReasons permissions removed successfully');
}
