/**
 * Migration: Add Contracts Permissions
 *
 * Creates contracts role and permissions with role hierarchy support.
 * The contracts role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates contracts role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: contracts (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under contracts later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:contracts
 * Domain: inventory/master-data
 * Generated: 2025-12-07T07:36:36.908Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * Contracts permissions definition
 */
const CONTRACTS_PERMISSIONS = [
  {
    resource: 'inventory:contracts',
    action: 'create',
    description: 'Create contracts',
  },
  {
    resource: 'inventory:contracts',
    action: 'read',
    description: 'Read contracts',
  },
  {
    resource: 'inventory:contracts',
    action: 'update',
    description: 'Update contracts',
  },
  {
    resource: 'inventory:contracts',
    action: 'delete',
    description: 'Delete contracts',
  },
  {
    resource: 'inventory:contracts',
    action: 'export',
    description: 'Export contracts',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating contracts role and permissions...');

  // Step 1: Create contracts role with admin as parent
  // This ensures contracts role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'contracts',
    'Contracts module role',
    'admin',
  );

  // Step 2: Create permissions and assign to contracts role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, CONTRACTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'contracts',
        permissions: CONTRACTS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] Contracts role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing contracts permissions...');

  await removePermissions(knex, CONTRACTS_PERMISSIONS);

  console.log('[Migration] Contracts permissions removed successfully');
}
