/**
 * Migration: Add Companies Permissions
 *
 * Creates companies role and permissions with role hierarchy support.
 * The companies role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates companies role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: companies (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under companies later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:companies
 * Domain: inventory/master-data
 * Generated: 2025-12-08T02:04:07.498Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * Companies permissions definition
 */
const COMPANIES_PERMISSIONS = [
  {
    resource: 'inventory:companies',
    action: 'create',
    description: 'Create companies',
  },
  {
    resource: 'inventory:companies',
    action: 'read',
    description: 'Read companies',
  },
  {
    resource: 'inventory:companies',
    action: 'update',
    description: 'Update companies',
  },
  {
    resource: 'inventory:companies',
    action: 'delete',
    description: 'Delete companies',
  },
  {
    resource: 'inventory:companies',
    action: 'export',
    description: 'Export companies',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating companies role and permissions...');

  // Step 1: Create companies role with admin as parent
  // This ensures companies role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'companies',
    'Companies module role',
    'admin',
  );

  // Step 2: Create permissions and assign to companies role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, COMPANIES_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'companies',
        permissions: COMPANIES_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] Companies role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing companies permissions...');

  await removePermissions(knex, COMPANIES_PERMISSIONS);

  console.log('[Migration] Companies permissions removed successfully');
}
