/**
 * Migration: Add DrugPackRatios Permissions
 *
 * Creates drugPackRatios role and permissions with role hierarchy support.
 * The drugPackRatios role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugPackRatios role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: drugPackRatios (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugPackRatios later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:drugPackRatios
 * Domain: inventory/master-data
 * Generated: 2025-12-07T07:44:55.718Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DrugPackRatios permissions definition
 */
const DRUGPACKRATIOS_PERMISSIONS = [
  {
    resource: 'inventory:drugPackRatios',
    action: 'create',
    description: 'Create drugPackRatios',
  },
  {
    resource: 'inventory:drugPackRatios',
    action: 'read',
    description: 'Read drugPackRatios',
  },
  {
    resource: 'inventory:drugPackRatios',
    action: 'update',
    description: 'Update drugPackRatios',
  },
  {
    resource: 'inventory:drugPackRatios',
    action: 'delete',
    description: 'Delete drugPackRatios',
  },
  {
    resource: 'inventory:drugPackRatios',
    action: 'export',
    description: 'Export drugPackRatios',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating drugPackRatios role and permissions...');

  // Step 1: Create drugPackRatios role with admin as parent
  // This ensures drugPackRatios role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'drugPackRatios',
    'DrugPackRatios module role',
    'admin',
  );

  // Step 2: Create permissions and assign to drugPackRatios role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, DRUGPACKRATIOS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugPackRatios',
        permissions: DRUGPACKRATIOS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] DrugPackRatios role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugPackRatios permissions...');

  await removePermissions(knex, DRUGPACKRATIOS_PERMISSIONS);

  console.log('[Migration] DrugPackRatios permissions removed successfully');
}
