/**
 * Migration: Add HospitalPharmaceuticalProducts Permissions
 *
 * Creates hospitalPharmaceuticalProducts role and permissions with role hierarchy support.
 * The hospitalPharmaceuticalProducts role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates hospitalPharmaceuticalProducts role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: hospitalPharmaceuticalProducts (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under hospitalPharmaceuticalProducts later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:hospitalPharmaceuticalProducts
 * Domain: inventory/master-data
 * Generated: 2025-12-05T21:18:44.375Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * HospitalPharmaceuticalProducts permissions definition
 */
const HOSPITALPHARMACEUTICALPRODUCTS_PERMISSIONS = [
  {
    resource: 'inventory:hospitalPharmaceuticalProducts',
    action: 'create',
    description: 'Create hospitalPharmaceuticalProducts',
  },
  {
    resource: 'inventory:hospitalPharmaceuticalProducts',
    action: 'read',
    description: 'Read hospitalPharmaceuticalProducts',
  },
  {
    resource: 'inventory:hospitalPharmaceuticalProducts',
    action: 'update',
    description: 'Update hospitalPharmaceuticalProducts',
  },
  {
    resource: 'inventory:hospitalPharmaceuticalProducts',
    action: 'delete',
    description: 'Delete hospitalPharmaceuticalProducts',
  },
  {
    resource: 'inventory:hospitalPharmaceuticalProducts',
    action: 'export',
    description: 'Export hospitalPharmaceuticalProducts',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log(
    '[Migration] Creating hospitalPharmaceuticalProducts role and permissions...',
  );

  // Step 1: Create hospitalPharmaceuticalProducts role with admin as parent
  // This ensures hospitalPharmaceuticalProducts role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'hospitalPharmaceuticalProducts',
    'HospitalPharmaceuticalProducts module role',
    'admin',
  );

  // Step 2: Create permissions and assign to hospitalPharmaceuticalProducts role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, HOSPITALPHARMACEUTICALPRODUCTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'hospitalPharmaceuticalProducts',
        permissions: HOSPITALPHARMACEUTICALPRODUCTS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] HospitalPharmaceuticalProducts role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log(
    '[Migration] Removing hospitalPharmaceuticalProducts permissions...',
  );

  await removePermissions(knex, HOSPITALPHARMACEUTICALPRODUCTS_PERMISSIONS);

  console.log(
    '[Migration] HospitalPharmaceuticalProducts permissions removed successfully',
  );
}
