/**
 * Migration: Add BudgetPlans Permissions
 *
 * Creates budgetPlans role and permissions with role hierarchy support.
 * The budgetPlans role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates budgetPlans role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: budgetPlans (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under budgetPlans later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:budgetPlans
 * Domain: inventory/operations
 * Generated: 2025-12-08T03:33:53.039Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * BudgetPlans permissions definition
 */
const BUDGETPLANS_PERMISSIONS = [
  {
    resource: 'inventory:budgetPlans',
    action: 'create',
    description: 'Create budgetPlans',
  },
  {
    resource: 'inventory:budgetPlans',
    action: 'read',
    description: 'Read budgetPlans',
  },
  {
    resource: 'inventory:budgetPlans',
    action: 'update',
    description: 'Update budgetPlans',
  },
  {
    resource: 'inventory:budgetPlans',
    action: 'delete',
    description: 'Delete budgetPlans',
  },
  {
    resource: 'inventory:budgetPlans',
    action: 'export',
    description: 'Export budgetPlans',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating budgetPlans role and permissions...');

  // Step 1: Create budgetPlans role with admin as parent
  // This ensures budgetPlans role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'budgetPlans',
    'BudgetPlans module role',
    'admin',
  );

  // Step 2: Create permissions and assign to budgetPlans role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, BUDGETPLANS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'budgetPlans',
        permissions: BUDGETPLANS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] BudgetPlans role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing budgetPlans permissions...');

  await removePermissions(knex, BUDGETPLANS_PERMISSIONS);

  console.log('[Migration] BudgetPlans permissions removed successfully');
}
