/**
 * Migration: Add DistributionTypes Permissions
 *
 * Creates distributionTypes role and permissions with role hierarchy support.
 * The distributionTypes role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates distributionTypes role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: distributionTypes (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under distributionTypes later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:distributionTypes
 * Domain: inventory/master-data
 * Generated: 2025-12-05T21:20:34.188Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DistributionTypes permissions definition
 */
const DISTRIBUTIONTYPES_PERMISSIONS = [
  {
    resource: 'inventory:distributionTypes',
    action: 'create',
    description: 'Create distributionTypes',
  },
  {
    resource: 'inventory:distributionTypes',
    action: 'read',
    description: 'Read distributionTypes',
  },
  {
    resource: 'inventory:distributionTypes',
    action: 'update',
    description: 'Update distributionTypes',
  },
  {
    resource: 'inventory:distributionTypes',
    action: 'delete',
    description: 'Delete distributionTypes',
  },
  {
    resource: 'inventory:distributionTypes',
    action: 'export',
    description: 'Export distributionTypes',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating distributionTypes role and permissions...');

  // Step 1: Create distributionTypes role with admin as parent
  // This ensures distributionTypes role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'distributionTypes',
    'DistributionTypes module role',
    'admin',
  );

  // Step 2: Create permissions and assign to distributionTypes role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, DISTRIBUTIONTYPES_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'distributionTypes',
        permissions: DISTRIBUTIONTYPES_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] DistributionTypes role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing distributionTypes permissions...');

  await removePermissions(knex, DISTRIBUTIONTYPES_PERMISSIONS);

  console.log('[Migration] DistributionTypes permissions removed successfully');
}
