/**
 * Migration: Add Inventory Permissions
 *
 * Creates inventory role and permissions with role hierarchy support.
 * The inventory role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates inventory role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: inventory (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under inventory later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:inventory
 * Domain: inventory/master-data
 * Generated: 2025-12-05T21:18:48.832Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * Inventory permissions definition
 */
const INVENTORY_PERMISSIONS = [
  {
    resource: 'inventory:inventory',
    action: 'create',
    description: 'Create inventory',
  },
  {
    resource: 'inventory:inventory',
    action: 'read',
    description: 'Read inventory',
  },
  {
    resource: 'inventory:inventory',
    action: 'update',
    description: 'Update inventory',
  },
  {
    resource: 'inventory:inventory',
    action: 'delete',
    description: 'Delete inventory',
  },
  {
    resource: 'inventory:inventory',
    action: 'export',
    description: 'Export inventory',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating inventory role and permissions...');

  // Step 1: Create inventory role with admin as parent
  // This ensures inventory role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'inventory',
    'Inventory module role',
    'admin',
  );

  // Step 2: Create permissions and assign to inventory role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, INVENTORY_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'inventory',
        permissions: INVENTORY_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] Inventory role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing inventory permissions...');

  await removePermissions(knex, INVENTORY_PERMISSIONS);

  console.log('[Migration] Inventory permissions removed successfully');
}
