/**
 * Migration: Add TmtMappings Permissions
 *
 * Creates tmtMappings role and permissions with role hierarchy support.
 * The tmtMappings role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates tmtMappings role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: tmtMappings (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under tmtMappings later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:tmtMappings
 * Domain: inventory/master-data
 * Generated: 2025-12-05T21:18:56.346Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * TmtMappings permissions definition
 */
const TMTMAPPINGS_PERMISSIONS = [
  {
    resource: 'inventory:tmtMappings',
    action: 'create',
    description: 'Create tmtMappings',
  },
  {
    resource: 'inventory:tmtMappings',
    action: 'read',
    description: 'Read tmtMappings',
  },
  {
    resource: 'inventory:tmtMappings',
    action: 'update',
    description: 'Update tmtMappings',
  },
  {
    resource: 'inventory:tmtMappings',
    action: 'delete',
    description: 'Delete tmtMappings',
  },
  {
    resource: 'inventory:tmtMappings',
    action: 'export',
    description: 'Export tmtMappings',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating tmtMappings role and permissions...');

  // Step 1: Create tmtMappings role with admin as parent
  // This ensures tmtMappings role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'tmtMappings',
    'TmtMappings module role',
    'admin',
  );

  // Step 2: Create permissions and assign to tmtMappings role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, TMTMAPPINGS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'tmtMappings',
        permissions: TMTMAPPINGS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] TmtMappings role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing tmtMappings permissions...');

  await removePermissions(knex, TMTMAPPINGS_PERMISSIONS);

  console.log('[Migration] TmtMappings permissions removed successfully');
}
