/**
 * Migration: Add ReturnActions Permissions
 *
 * Creates returnActions role and permissions with role hierarchy support.
 * The returnActions role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates returnActions role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: returnActions (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under returnActions later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:returnActions
 * Domain: inventory/master-data
 * Generated: 2025-12-07T07:38:43.109Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * ReturnActions permissions definition
 */
const RETURNACTIONS_PERMISSIONS = [
  {
    resource: 'inventory:returnActions',
    action: 'create',
    description: 'Create returnActions',
  },
  {
    resource: 'inventory:returnActions',
    action: 'read',
    description: 'Read returnActions',
  },
  {
    resource: 'inventory:returnActions',
    action: 'update',
    description: 'Update returnActions',
  },
  {
    resource: 'inventory:returnActions',
    action: 'delete',
    description: 'Delete returnActions',
  },
  {
    resource: 'inventory:returnActions',
    action: 'export',
    description: 'Export returnActions',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating returnActions role and permissions...');

  // Step 1: Create returnActions role with admin as parent
  // This ensures returnActions role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'returnActions',
    'ReturnActions module role',
    'admin',
  );

  // Step 2: Create permissions and assign to returnActions role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, RETURNACTIONS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'returnActions',
        permissions: RETURNACTIONS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] ReturnActions role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing returnActions permissions...');

  await removePermissions(knex, RETURNACTIONS_PERMISSIONS);

  console.log('[Migration] ReturnActions permissions removed successfully');
}
