/**
 * Migration: Add PurchaseTypes Permissions
 *
 * Creates purchaseTypes role and permissions with role hierarchy support.
 * The purchaseTypes role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates purchaseTypes role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: purchaseTypes (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under purchaseTypes later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:purchaseTypes
 * Domain: inventory/master-data
 * Generated: 2025-12-05T21:21:20.648Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * PurchaseTypes permissions definition
 */
const PURCHASETYPES_PERMISSIONS = [
  {
    resource: 'inventory:purchaseTypes',
    action: 'create',
    description: 'Create purchaseTypes',
  },
  {
    resource: 'inventory:purchaseTypes',
    action: 'read',
    description: 'Read purchaseTypes',
  },
  {
    resource: 'inventory:purchaseTypes',
    action: 'update',
    description: 'Update purchaseTypes',
  },
  {
    resource: 'inventory:purchaseTypes',
    action: 'delete',
    description: 'Delete purchaseTypes',
  },
  {
    resource: 'inventory:purchaseTypes',
    action: 'export',
    description: 'Export purchaseTypes',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating purchaseTypes role and permissions...');

  // Step 1: Create purchaseTypes role with admin as parent
  // This ensures purchaseTypes role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'purchaseTypes',
    'PurchaseTypes module role',
    'admin',
  );

  // Step 2: Create permissions and assign to purchaseTypes role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, PURCHASETYPES_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'purchaseTypes',
        permissions: PURCHASETYPES_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] PurchaseTypes role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing purchaseTypes permissions...');

  await removePermissions(knex, PURCHASETYPES_PERMISSIONS);

  console.log('[Migration] PurchaseTypes permissions removed successfully');
}
