/**
 * Migration: Add DrugLots Permissions
 *
 * Creates drugLots role and permissions with role hierarchy support.
 * The drugLots role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugLots role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: drugLots (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugLots later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:drugLots
 * Domain: inventory/master-data
 * Generated: 2025-12-05T21:18:04.094Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DrugLots permissions definition
 */
const DRUGLOTS_PERMISSIONS = [
  {
    resource: 'inventory:drugLots',
    action: 'create',
    description: 'Create drugLots',
  },
  {
    resource: 'inventory:drugLots',
    action: 'read',
    description: 'Read drugLots',
  },
  {
    resource: 'inventory:drugLots',
    action: 'update',
    description: 'Update drugLots',
  },
  {
    resource: 'inventory:drugLots',
    action: 'delete',
    description: 'Delete drugLots',
  },
  {
    resource: 'inventory:drugLots',
    action: 'export',
    description: 'Export drugLots',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating drugLots role and permissions...');

  // Step 1: Create drugLots role with admin as parent
  // This ensures drugLots role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'drugLots',
    'DrugLots module role',
    'admin',
  );

  // Step 2: Create permissions and assign to drugLots role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, DRUGLOTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugLots',
        permissions: DRUGLOTS_PERMISSIONS,
      },
    ],
  });

  console.log('[Migration] DrugLots role and permissions created successfully');
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugLots permissions...');

  await removePermissions(knex, DRUGLOTS_PERMISSIONS);

  console.log('[Migration] DrugLots permissions removed successfully');
}
