/**
 * Migration: Add BudgetRequests Permissions
 *
 * Creates budgetRequests role and permissions with role hierarchy support.
 * The budgetRequests role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates budgetRequests role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: budgetRequests (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under budgetRequests later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:budgetRequests
 * Domain: inventory/budget
 * Generated: 2025-12-08T07:49:07.482Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * BudgetRequests permissions definition
 * Includes standard CRUD + workflow-specific actions
 */
const BUDGETREQUESTS_PERMISSIONS = [
  {
    resource: 'inventory:budgetRequests',
    action: 'create',
    description: 'Create budgetRequests',
  },
  {
    resource: 'inventory:budgetRequests',
    action: 'read',
    description: 'Read budgetRequests',
  },
  {
    resource: 'inventory:budgetRequests',
    action: 'update',
    description: 'Update budgetRequests',
  },
  {
    resource: 'inventory:budgetRequests',
    action: 'delete',
    description: 'Delete budgetRequests',
  },
  {
    resource: 'inventory:budgetRequests',
    action: 'export',
    description: 'Export budgetRequests',
  },
  // Workflow-specific permissions
  {
    resource: 'inventory:budgetRequests',
    action: 'submit',
    description: 'Submit budget request for approval',
  },
  {
    resource: 'inventory:budgetRequests',
    action: 'approve_dept',
    description: 'Approve budget request as department head',
  },
  {
    resource: 'inventory:budgetRequests',
    action: 'approve_finance',
    description: 'Approve budget request as finance manager',
  },
  {
    resource: 'inventory:budgetRequests',
    action: 'reject',
    description: 'Reject budget request',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating budgetRequests role and permissions...');

  // Step 1: Create budgetRequests role with admin as parent
  // This ensures budgetRequests role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'budgetRequests',
    'BudgetRequests module role',
    'admin',
  );

  // Step 2: Create permissions and assign to budgetRequests role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, BUDGETREQUESTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'budgetRequests',
        permissions: BUDGETREQUESTS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] BudgetRequests role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing budgetRequests permissions...');

  await removePermissions(knex, BUDGETREQUESTS_PERMISSIONS);

  console.log('[Migration] BudgetRequests permissions removed successfully');
}
