/**
 * Migration: Add DrugGenerics Permissions
 *
 * Creates drugGenerics role and permissions with role hierarchy support.
 * The drugGenerics role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugGenerics role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: drugGenerics (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugGenerics later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:drugGenerics
 * Domain: inventory/master-data
 * Generated: 2025-12-05T21:20:50.782Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DrugGenerics permissions definition
 */
const DRUGGENERICS_PERMISSIONS = [
  {
    resource: 'inventory:drugGenerics',
    action: 'create',
    description: 'Create drugGenerics',
  },
  {
    resource: 'inventory:drugGenerics',
    action: 'read',
    description: 'Read drugGenerics',
  },
  {
    resource: 'inventory:drugGenerics',
    action: 'update',
    description: 'Update drugGenerics',
  },
  {
    resource: 'inventory:drugGenerics',
    action: 'delete',
    description: 'Delete drugGenerics',
  },
  {
    resource: 'inventory:drugGenerics',
    action: 'export',
    description: 'Export drugGenerics',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating drugGenerics role and permissions...');

  // Step 1: Create drugGenerics role with admin as parent
  // This ensures drugGenerics role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'drugGenerics',
    'DrugGenerics module role',
    'admin',
  );

  // Step 2: Create permissions and assign to drugGenerics role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, DRUGGENERICS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugGenerics',
        permissions: DRUGGENERICS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] DrugGenerics role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugGenerics permissions...');

  await removePermissions(knex, DRUGGENERICS_PERMISSIONS);

  console.log('[Migration] DrugGenerics permissions removed successfully');
}
