/**
 * Migration: Add DrugUnits Permissions
 *
 * Creates drugUnits role and permissions with role hierarchy support.
 * The drugUnits role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugUnits role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: drugUnits (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugUnits later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:drugUnits
 * Domain: inventory/master-data
 * Generated: 2025-12-08T02:05:18.392Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DrugUnits permissions definition
 */
const DRUGUNITS_PERMISSIONS = [
  {
    resource: 'inventory:drugUnits',
    action: 'create',
    description: 'Create drugUnits',
  },
  {
    resource: 'inventory:drugUnits',
    action: 'read',
    description: 'Read drugUnits',
  },
  {
    resource: 'inventory:drugUnits',
    action: 'update',
    description: 'Update drugUnits',
  },
  {
    resource: 'inventory:drugUnits',
    action: 'delete',
    description: 'Delete drugUnits',
  },
  {
    resource: 'inventory:drugUnits',
    action: 'export',
    description: 'Export drugUnits',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating drugUnits role and permissions...');

  // Step 1: Create drugUnits role with admin as parent
  // This ensures drugUnits role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'drugUnits',
    'DrugUnits module role',
    'admin',
  );

  // Step 2: Create permissions and assign to drugUnits role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, DRUGUNITS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugUnits',
        permissions: DRUGUNITS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] DrugUnits role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugUnits permissions...');

  await removePermissions(knex, DRUGUNITS_PERMISSIONS);

  console.log('[Migration] DrugUnits permissions removed successfully');
}
