/**
 * Migration: Add BudgetAllocations Permissions
 *
 * Creates budgetAllocations role and permissions with role hierarchy support.
 * The budgetAllocations role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates budgetAllocations role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: budgetAllocations (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under budgetAllocations later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:budgetAllocations
 * Domain: inventory/operations
 * Generated: 2025-12-08T03:33:44.847Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * BudgetAllocations permissions definition
 */
const BUDGETALLOCATIONS_PERMISSIONS = [
  {
    resource: 'inventory:budgetAllocations',
    action: 'create',
    description: 'Create budgetAllocations',
  },
  {
    resource: 'inventory:budgetAllocations',
    action: 'read',
    description: 'Read budgetAllocations',
  },
  {
    resource: 'inventory:budgetAllocations',
    action: 'update',
    description: 'Update budgetAllocations',
  },
  {
    resource: 'inventory:budgetAllocations',
    action: 'delete',
    description: 'Delete budgetAllocations',
  },
  {
    resource: 'inventory:budgetAllocations',
    action: 'export',
    description: 'Export budgetAllocations',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating budgetAllocations role and permissions...');

  // Step 1: Create budgetAllocations role with admin as parent
  // This ensures budgetAllocations role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'budgetAllocations',
    'BudgetAllocations module role',
    'admin',
  );

  // Step 2: Create permissions and assign to budgetAllocations role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, BUDGETALLOCATIONS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'budgetAllocations',
        permissions: BUDGETALLOCATIONS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] BudgetAllocations role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing budgetAllocations permissions...');

  await removePermissions(knex, BUDGETALLOCATIONS_PERMISSIONS);

  console.log('[Migration] BudgetAllocations permissions removed successfully');
}
