/**
 * Migration: Add DrugComponents Permissions
 *
 * Creates drugComponents role and permissions with role hierarchy support.
 * The drugComponents role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugComponents role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: drugComponents (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugComponents later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:drugComponents
 * Domain: inventory/master-data
 * Generated: 2025-12-07T07:44:24.236Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DrugComponents permissions definition
 */
const DRUGCOMPONENTS_PERMISSIONS = [
  {
    resource: 'inventory:drugComponents',
    action: 'create',
    description: 'Create drugComponents',
  },
  {
    resource: 'inventory:drugComponents',
    action: 'read',
    description: 'Read drugComponents',
  },
  {
    resource: 'inventory:drugComponents',
    action: 'update',
    description: 'Update drugComponents',
  },
  {
    resource: 'inventory:drugComponents',
    action: 'delete',
    description: 'Delete drugComponents',
  },
  {
    resource: 'inventory:drugComponents',
    action: 'export',
    description: 'Export drugComponents',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating drugComponents role and permissions...');

  // Step 1: Create drugComponents role with admin as parent
  // This ensures drugComponents role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'drugComponents',
    'DrugComponents module role',
    'admin',
  );

  // Step 2: Create permissions and assign to drugComponents role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, DRUGCOMPONENTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugComponents',
        permissions: DRUGCOMPONENTS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] DrugComponents role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugComponents permissions...');

  await removePermissions(knex, DRUGCOMPONENTS_PERMISSIONS);

  console.log('[Migration] DrugComponents permissions removed successfully');
}
