/**
 * Migration: Add Locations Permissions
 *
 * Creates locations role and permissions with role hierarchy support.
 * The locations role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates locations role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: locations (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under locations later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:locations
 * Domain: inventory/master-data
 * Generated: 2025-12-05T21:21:12.564Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * Locations permissions definition
 */
const LOCATIONS_PERMISSIONS = [
  {
    resource: 'inventory:locations',
    action: 'create',
    description: 'Create locations',
  },
  {
    resource: 'inventory:locations',
    action: 'read',
    description: 'Read locations',
  },
  {
    resource: 'inventory:locations',
    action: 'update',
    description: 'Update locations',
  },
  {
    resource: 'inventory:locations',
    action: 'delete',
    description: 'Delete locations',
  },
  {
    resource: 'inventory:locations',
    action: 'export',
    description: 'Export locations',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating locations role and permissions...');

  // Step 1: Create locations role with admin as parent
  // This ensures locations role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'locations',
    'Locations module role',
    'admin',
  );

  // Step 2: Create permissions and assign to locations role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, LOCATIONS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'locations',
        permissions: LOCATIONS_PERMISSIONS,
      },
    ],
  });

  console.log(
    '[Migration] Locations role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing locations permissions...');

  await removePermissions(knex, LOCATIONS_PERMISSIONS);

  console.log('[Migration] Locations permissions removed successfully');
}
