/**
 * Migration: Add BudgetPlanItems Permissions
 *
 * Creates budgetPlanItems role and permissions with role hierarchy support.
 * The budgetPlanItems role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates budgetPlanItems role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: budgetPlanItems (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under budgetPlanItems later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:budgetPlanItems
 * Domain: inventory/operations
 * Generated: 2025-12-08T03:34:00.038Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * BudgetPlanItems permissions definition
 */
const BUDGETPLANITEMS_PERMISSIONS = [
  {
    resource: 'inventory:budgetPlanItems',
    action: 'create',
    description: 'Create budgetPlanItems',
  },
  {
    resource: 'inventory:budgetPlanItems',
    action: 'read',
    description: 'Read budgetPlanItems',
  },
  {
    resource: 'inventory:budgetPlanItems',
    action: 'update',
    description: 'Update budgetPlanItems',
  },
  {
    resource: 'inventory:budgetPlanItems',
    action: 'delete',
    description: 'Delete budgetPlanItems',
  },
  {
    resource: 'inventory:budgetPlanItems',
    action: 'export',
    description: 'Export budgetPlanItems',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating budgetPlanItems role and permissions...');

  // Step 1: Create budgetPlanItems role with admin as parent
  // This ensures budgetPlanItems role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'budgetPlanItems',
    'BudgetPlanItems module role',
    'admin',
  );

  // Step 2: Create permissions and assign to budgetPlanItems role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, BUDGETPLANITEMS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'budgetPlanItems',
        permissions: BUDGETPLANITEMS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] BudgetPlanItems role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing budgetPlanItems permissions...');

  await removePermissions(knex, BUDGETPLANITEMS_PERMISSIONS);

  console.log('[Migration] BudgetPlanItems permissions removed successfully');
}
