/**
 * Migration: Add Bank Permissions
 *
 * Creates bank role and permissions with role hierarchy support.
 * The bank role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates bank role and links all permissions to it
 * - Admin inheritance: Admin role inherits permissions automatically
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL)
 * - Level 2: bank (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under bank later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:bank
 * Domain: inventory/master-data
 * Generated: 2025-12-07T07:37:09.301Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * Bank permissions definition
 */
const BANK_PERMISSIONS = [
  {
    resource: 'inventory:bank',
    action: 'create',
    description: 'Create bank',
  },
  {
    resource: 'inventory:bank',
    action: 'read',
    description: 'Read bank',
  },
  {
    resource: 'inventory:bank',
    action: 'update',
    description: 'Update bank',
  },
  {
    resource: 'inventory:bank',
    action: 'delete',
    description: 'Delete bank',
  },
  {
    resource: 'inventory:bank',
    action: 'export',
    description: 'Export bank',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating bank role and permissions...');

  // Step 1: Create bank role with admin as parent
  // This ensures bank role is part of the hierarchy
  await createRoleIfNotExists(knex, 'bank', 'Bank module role', 'admin');

  // Step 2: Create permissions and assign to bank role
  // Admin will inherit these permissions automatically via parent_id hierarchy
  await createPermissions(knex, BANK_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'bank',
        permissions: BANK_PERMISSIONS,
      },
    ],
  });

  console.log('[Migration] Bank role and permissions created successfully');
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing bank permissions...');

  await removePermissions(knex, BANK_PERMISSIONS);

  console.log('[Migration] Bank permissions removed successfully');
}
