name: 🔒 Security Vulnerability Report
description: Report a security vulnerability or concern
title: "[SECURITY] "
labels: ["security", "bug", "high-priority"]
assignees:
  - aegisx-security
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ IMPORTANT: Please DO NOT create a public issue for security vulnerabilities.**
        
        If you believe you have found a security vulnerability, please report it privately:
        1. Email security@aegisx.com
        2. Use GitHub Security Advisory (preferred)
        3. Contact us via our security disclosure program
        
        This template is for security-related bugs that are not vulnerabilities.
        
  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security concern?
      options:
        - Low (Informational)
        - Medium (Potential risk)
        - High (Active risk)
        - Critical (Immediate action required)
      default: 1
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Security Concern Description
      description: Describe the security concern without revealing sensitive details
      placeholder: Brief description of the security concern...
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the system is affected?
      options:
        - API (Backend)
        - Web Application (Frontend)
        - Admin Panel
        - Database
        - Infrastructure/DevOps
        - Documentation
        - Other
    validations:
      required: true
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Security Checklist
      description: Please confirm the following
      options:
        - label: I have not included sensitive information in this public issue
          required: true
        - label: I have checked that this is not a duplicate issue
          required: true
        - label: I understand that security vulnerabilities should be reported privately
          required: true