import type { Knex } from 'knex';

/**
 * Migration: Add ComprehensiveTests permissions and roles
 * Generated by CRUD Generator on 2025-10-06T07:56:04.845Z
 */

export async function up(knex: Knex): Promise<void> {
  console.log('🔐 Adding ComprehensiveTests permissions and roles...');

  // Insert permissions for comprehensiveTests
  const permissions = [
    {
      description: 'Create comprehensiveTests',
      resource: 'comprehensiveTests',
      action: 'create',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Read comprehensiveTests',
      resource: 'comprehensiveTests',
      action: 'read',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Update comprehensiveTests',
      resource: 'comprehensiveTests',
      action: 'update',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Delete comprehensiveTests',
      resource: 'comprehensiveTests',
      action: 'delete',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(
    `📝 Inserting ${permissions.length} permissions for comprehensiveTests...`,
  );
  await knex('permissions')
    .insert(permissions)
    .onConflict(['resource', 'action'])
    .ignore();

  // Insert roles for comprehensiveTests
  const roles = [
    {
      name: 'comprehensiveTests',
      description: 'Access to comprehensiveTests',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`🏷️  Inserting ${roles.length} roles for comprehensiveTests...`);
  await knex('roles').insert(roles).onConflict('name').ignore();

  // Link role permissions
  // comprehensiveTests role permissions
  const mainRole = await knex('roles')
    .where('name', 'comprehensiveTests')
    .first();
  if (mainRole) {
    const mainPermissions = await knex('permissions')
      .where('resource', 'comprehensiveTests')
      .whereIn('action', ['create', 'read', 'update', 'delete'])
      .select('id');

    if (mainPermissions.length > 0) {
      const rolePermissions = mainPermissions.map((p) => ({
        role_id: mainRole.id,
        permission_id: p.id,
        created_at: new Date(),
      }));

      console.log(
        `🔗 Linking ${mainPermissions.length} permissions to comprehensiveTests role...`,
      );
      await knex('role_permissions')
        .insert(rolePermissions)
        .onConflict(['role_id', 'permission_id'])
        .ignore();
    }
  }

  console.log('✅ ComprehensiveTests permissions and roles added successfully');
}

export async function down(knex: Knex): Promise<void> {
  console.log('🗑️  Removing ComprehensiveTests permissions and roles...');

  // Remove role permissions first
  const roleIds = await knex('roles')
    .whereIn('name', ['comprehensiveTests'])
    .pluck('id');

  if (roleIds.length > 0) {
    console.log(`🔗 Removing role permissions for comprehensiveTests...`);
    await knex('role_permissions').whereIn('role_id', roleIds).del();
  }

  // Remove roles
  console.log(`🏷️  Removing comprehensiveTests role...`);
  const deletedRoles = await knex('roles')
    .whereIn('name', ['comprehensiveTests'])
    .del();

  // Remove permissions
  console.log(`📝 Removing comprehensiveTests permissions...`);
  const deletedPermissions = await knex('permissions')
    .where('resource', 'comprehensiveTests')
    .del();

  console.log(
    `✅ Removed ${deletedRoles} roles and ${deletedPermissions} permissions for comprehensiveTests`,
  );
}
