import type { Knex } from 'knex';

/**
 * Migration: Add Articles permissions and roles
 * Generated by CRUD Generator on 2025-10-04T00:05:06.000Z
 */

export async function up(knex: Knex): Promise<void> {
  console.log('🔐 Adding Articles permissions and roles...');

  // Insert permissions for articles
  const permissions = [
    {
      description: 'Create articles',
      resource: 'articles',
      action: 'create',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Read articles',
      resource: 'articles',
      action: 'read',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Update articles',
      resource: 'articles',
      action: 'update',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Delete articles',
      resource: 'articles',
      action: 'delete',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`📝 Inserting ${permissions.length} permissions for articles...`);
  await knex('permissions')
    .insert(permissions)
    .onConflict(['resource', 'action'])
    .ignore();

  // Insert roles for articles
  const roles = [
    {
      name: 'articles',
      description: 'Access to articles',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`🏷️  Inserting ${roles.length} roles for articles...`);
  await knex('roles').insert(roles).onConflict('name').ignore();

  // Link role permissions
  // articles role permissions
  const mainRole = await knex('roles').where('name', 'articles').first();
  if (mainRole) {
    const mainPermissions = await knex('permissions')
      .where('resource', 'articles')
      .whereIn('action')
      .select('id');

    if (mainPermissions.length > 0) {
      const rolePermissions = mainPermissions.map((p) => ({
        role_id: mainRole.id,
        permission_id: p.id,
        created_at: new Date(),
      }));

      console.log(
        `🔗 Linking ${mainPermissions.length} permissions to articles role...`,
      );
      await knex('role_permissions')
        .insert(rolePermissions)
        .onConflict(['role_id', 'permission_id'])
        .ignore();
    }
  }

  console.log('✅ Articles permissions and roles added successfully');
}

export async function down(knex: Knex): Promise<void> {
  console.log('🗑️  Removing Articles permissions and roles...');

  // Remove role permissions first
  const roleIds = await knex('roles').whereIn('name', ['articles']).pluck('id');

  if (roleIds.length > 0) {
    console.log(`🔗 Removing role permissions for articles...`);
    await knex('role_permissions').whereIn('role_id', roleIds).del();
  }

  // Remove roles
  console.log(`🏷️  Removing articles role...`);
  const deletedRoles = await knex('roles').whereIn('name', ['articles']).del();

  // Remove permissions
  console.log(`📝 Removing articles permissions...`);
  const deletedPermissions = await knex('permissions')
    .where('resource', 'articles')
    .del();

  console.log(
    `✅ Removed ${deletedRoles} roles and ${deletedPermissions} permissions for articles`,
  );
}
